### ISSUE TITLE
Fix PRIMARY KEY with AUTOINCREMENT problem (Northwind test database)

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#174]
```sql
CREATE TABLE [Categories]
(      [CategoryID] INTEGER PRIMARY KEY AUTOINCREMENT,
       [CategoryName] TEXT,
       [Description] TEXT
);

INSERT INTO Categories VALUES(null,'Beverages','Soft drinks, coffees, teas, beers, and ales');
INSERT INTO Categories VALUES(null,'Condiments','Sweet and savory sauces, relishes, spreads, and seasonings');
```
gives:
```
    Error: Cannot insert record, because it already exists in primary key
```
See test284.js

**Comment by agershun** [comment]
The same in w3.sql:
```
CREATE TABLE Categories (
    CategoryID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    CategoryName NVARCHAR(255),
    Description NVARCHAR(255)
);
INSERT INTO Categories (CategoryName,Description) 
    VALUES ("Beverages","Soft drinks, coffees, teas, beers, and ales");
INSERT INTO Categories (CategoryName,Description) 
    VALUES ("Condiments","Sweet and savory sauces, relishes, spreads, and seasonings");
```

**Comment by agershun** [comment]
Fixed. WIll be included in 0.1.5

**Comment by adenkaplan** [comment]
Hi I use @module alasql
@version 0.4.5-develop-1576

But I guess this issue is still exist. Or it's my mistake. The code and console logs are like this;
```
insert: function(values) {
        var me = this;
        var vals = null;
        return {
            into: function(tablePath){
                if(values.constructor.name === "Array"){
                    vals = values;
                } else {
                    vals = [values];
                }
                alasql('INSERT INTO '+tablePath+' VALUES ?', vals);
            }
        };
}
```

```
goc.aladb.createStructureFromEntities()
DB Created : USERS
{id: "INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT", name: "NVARCHAR(20)", surname: "NVARCHAR(20)", age: "NUMBER"}
    age: "NUMBER"
    id: "INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT"
    name: "NVARCHAR(20)"
    surname: "NVARCHAR(20)"__proto__: Object
{id: "INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT", name: "NVARCHAR(20)", surname: "NVARCHAR(20)", message: "STRING"}
    id:"INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT"
    message:"STRING"
    name:"NVARCHAR(20)"
    surname:"NVARCHAR(20)"
goc.aladb.insert(new USER()).into("USERS.USER");
goc.aladb.select("* from USERS.USER")
[{…}]
0: 
   age: 0
   id: undefined
   name: ""
   surname: ""
   __proto__: 
       Objectlength: 1__proto__: Array(0)
```

Thanks for your help.

**Comment by adenkaplan** [comment]
http://jsfiddle.net/80smosgp/3/
alasql v.0.3.9 worked as expected
the result is: 

```
goc.aladb.createStructureFromEntities()
DB Created : USERS

TABLE Created: USER ->
{
    id: "INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT", 
    name: "NVARCHAR(20)", 
    surname: "NVARCHAR(20)", 
    age: "NUMBER"
}

TABLE Created: MESSAGES ->
{
    id: "INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT",
    name: "NVARCHAR(20)",
    surname: "NVARCHAR(20)",
    message: "STRING"
}

goc.aladb.insert(new USER()).into("USERS.USER");
goc.aladb.insert(new USER()).into("USERS.USER");

goc.aladb.select("* from USERS.USER")
[{…}]
   0: {
        id: 1, 
        name: "", 
        surname: "", 
        age: 0
   }
   1: {
        id: 2, 
        name: "", 
        surname: "", 
        age: 0
   }
```

**Comment by mathiasrw** [comment]
As this task is closed I have extrated your inputs into #986
